title: <b>Shaan Sengupta</b>
description: Shaan Sengupta's Personal Website
theme: just-the-docs

url: https://shaan-sengupta.github.io/shaan-sengupta

search_enabled: false

#aux_links:
  #Template Repository: https://github.com/just-the-docs/just-the-docs-template
